import { copyFileSync, mkdirSync, readdirSync, existsSync, writeFileSync } from "node:fs";
import { resolve, join, relative } from "node:path";

const packageDir = resolve(import.meta.dirname, "..");
const tokenDir = resolve(packageDir, "..", "tokens", "generated");
const foundationsDir = resolve(packageDir, "src", "foundations");
const componentsDir = resolve(packageDir, "src", "components");
const distDir = resolve(packageDir, "dist");

mkdirSync(distDir, { recursive: true });

// Copy generated token assets
for (const file of ["tokens.css", "tokens.dark.css", "tokens.themes.css", "token-manifest.json"]) {
  copyFileSync(resolve(tokenDir, file), resolve(distDir, file));
}

// Copy foundation CSS files
const foundationsDistDir = resolve(distDir, "foundations");
mkdirSync(foundationsDistDir, { recursive: true });

if (existsSync(foundationsDir)) {
  for (const file of readdirSync(foundationsDir).filter((f) => f.endsWith(".css"))) {
    copyFileSync(resolve(foundationsDir, file), resolve(foundationsDistDir, file));
  }
}

// Copy component CSS files
const componentsDistDir = resolve(distDir, "components");
mkdirSync(componentsDistDir, { recursive: true });

const componentImports = [];

if (existsSync(componentsDir)) {
  for (const componentDir of readdirSync(componentsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()) {
    const componentPath = resolve(componentsDir, componentDir);
    const cssFiles = readdirSync(componentPath).filter((f) => f.endsWith(".css"));
    if (cssFiles.length === 0) continue;

    const componentDistDir = resolve(componentsDistDir, componentDir);
    mkdirSync(componentDistDir, { recursive: true });

    for (const cssFile of cssFiles) {
      copyFileSync(resolve(componentPath, cssFile), resolve(componentDistDir, cssFile));
    }

    componentImports.push(
      `@import "./components/${componentDir}/${cssFiles[0]}" layer(blora.components);`,
    );
  }
}

// Assemble and copy the full blora.css entry with @layer
const bloraCss = [
  "/* =========================================================================",
  "   Blora Design 2.0 - Full CSS entry (assembled)",
  "   DO NOT EDIT - generated by scripts/copy-tokens.mjs",
  "   ========================================================================= */",
  "",
  "@layer blora.tokens, blora.reset, blora.base, blora.components, blora.utilities;",
  "",
  `@import "./tokens.css" layer(blora.tokens);`,
  `@import "./foundations/reset.css" layer(blora.reset);`,
  `@import "./foundations/base.css" layer(blora.base);`,
  `@import "./foundations/layout.css" layer(blora.base);`,
  ...componentImports,
  `@import "./foundations/utilities.css" layer(blora.utilities);`,
  `@import "./tokens.themes.css" layer(blora.tokens);`,
  "",
].join("\n");

writeFileSync(resolve(distDir, "blora.css"), bloraCss);

// Also copy reset.css and foundations.css as standalone entries
copyFileSync(resolve(foundationsDir, "reset.css"), resolve(distDir, "reset.css"));

const foundationsEntry = [
  "/* Blora Design 2.0 - Foundations (reset + base + layout) */",
  `@import "./foundations/reset.css";`,
  `@import "./foundations/base.css";`,
  `@import "./foundations/layout.css";`,
  "",
].join("\n");
writeFileSync(resolve(distDir, "foundations.css"), foundationsEntry);

// Copy compat CSS
const compatDir = resolve(packageDir, "src", "compat", "v1");
if (existsSync(compatDir)) {
  const compatDistDir = resolve(distDir, "compat", "v1");
  mkdirSync(compatDistDir, { recursive: true });
  for (const file of readdirSync(compatDir).filter((f) => f.endsWith(".css"))) {
    copyFileSync(resolve(compatDir, file), resolve(compatDistDir, file));
  }
  // Also place at dist/compat/v1.css for the ./compat/v1.css export
  if (existsSync(resolve(compatDir, "v1.css"))) {
    copyFileSync(resolve(compatDir, "v1.css"), resolve(distDir, "compat", "v1.css"));
  }
}

console.log(
  "[copy-tokens] Copied token assets, foundations CSS, component CSS, compat CSS, and assembled blora.css into dist/.",
);
