import { copyFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const packageDir = resolve(import.meta.dirname, "..");
const tokenDir = resolve(packageDir, "..", "tokens", "generated");
const foundationsDir = resolve(packageDir, "src", "foundations");
const distDir = resolve(packageDir, "dist");

mkdirSync(distDir, { recursive: true });

// Copy generated token assets
for (const file of ["tokens.css", "tokens.dark.css", "tokens.themes.css", "token-manifest.json"]) {
  copyFileSync(resolve(tokenDir, file), resolve(distDir, file));
}

// Copy foundation CSS files
const foundationsDistDir = resolve(distDir, "foundations");
mkdirSync(foundationsDistDir, { recursive: true });

if (existsSync(foundationsDir)) {
  for (const file of readdirSync(foundationsDir).filter((f) => f.endsWith(".css"))) {
    copyFileSync(resolve(foundationsDir, file), resolve(foundationsDistDir, file));
  }
}

// Assemble and copy the full blora.css entry with @layer
const bloraCss = [
  "/* =========================================================================",
  "   Blora Design 2.0 - Full CSS entry (assembled)",
  "   DO NOT EDIT - generated by scripts/copy-tokens.mjs",
  "   ========================================================================= */",
  "",
  "@layer blora.tokens, blora.reset, blora.base, blora.components, blora.utilities;",
  "",
  `@import "./tokens.css" layer(blora.tokens);`,
  `@import "./foundations/reset.css" layer(blora.reset);`,
  `@import "./foundations/base.css" layer(blora.base);`,
  `@import "./foundations/layout.css" layer(blora.base);`,
  `@import "./foundations/utilities.css" layer(blora.utilities);`,
  `@import "./tokens.themes.css" layer(blora.tokens);`,
  "",
].join("\n");

const { writeFileSync } = await import("node:fs");
writeFileSync(resolve(distDir, "blora.css"), bloraCss);

// Also copy reset.css and foundations.css as standalone entries
copyFileSync(resolve(foundationsDir, "reset.css"), resolve(distDir, "reset.css"));

const foundationsEntry = [
  "/* Blora Design 2.0 - Foundations (reset + base + layout) */",
  `@import "./foundations/reset.css";`,
  `@import "./foundations/base.css";`,
  `@import "./foundations/layout.css";`,
  "",
].join("\n");
writeFileSync(resolve(distDir, "foundations.css"), foundationsEntry);

console.log(
  "[copy-tokens] Copied token assets, foundations CSS, and assembled blora.css into dist/.",
);
